//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int IdShipment { get; set; }
        public int IdProd { get; set; }
        public int IdSupplier { get; set; }
        public System.DateTime DateShipment { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
